extras/git-hooks/post-receive
It is really much more awesome.
With the old code we would generate exceptions if:
* The user pushed a git tag.
* The user pushed a commit signed with a gpg key.
Furthermore, it was just mistakenly written and it would only publish
one fedmsg even if multiple commits were pushed (it would only broadcast
about the latest commit).  This code actually publishes messages for
each commit on each branch.
Fixes #309.
=> Use the much more awesome pygit2.

fedmsg/crypto/__init__.py
There is a simple type-o in the config key that prevents this from working.
=> Fix ValueError when using gpg and gpg_home is not set

fedmsg/crypto/x509.py
This should fix the bug reported here:
https://bugzilla.redhat.com/show_bug.cgi?id=1189082
If there's a network error and the CRL is not reachable, currently
fedmsg just quietly returns the local path where the CRL should be, even
though it hasn't been downloaded.  This should surface that exception to
the user of the library.
=> Surface CRL errors.

fedmsg/meta/base.py, fedmsg/tests/test_meta.py
This should fix fedora-infra/fedmsg_meta_fedora_infrastructure#165.
=> Include constituent metadata in the conglomerate message.

fedmsg/consumers/__init__.py
Whoops!  Consumers can possibly declare their ``self.topic`` to be a list.
Here we get pages of results from datagrepper and only yield the messages
if the topic matches *any one* of the topics that we're interested in.
=> Handle multiple topics.

fedmsg/__init__.py
This is wild.
The symptom you'd get is this:  The *first* time
``fedmsg.publish(topic=topic, msg=dict(...))`` is ever called, fedmsg
isn't initialized yet.  Those topic and msg arguments are passed through
to ``init(**kw)`` as extra keyword arguments and so "topic" and "msg"
appear in the global config dict (internally).
This never mattered in practice.  They were there, and noone cared.
I'm hitting it now because in fmn, we try to call
``fedmsg.meta.msg2link(msg=msg, **config)`` but there is a ``msg`` key
in config from the first time ``publish`` was called and so it fails
with "cannot have two keyword arguments named 'msg'".
=> Scrub args from keywords before initializing.

extras/git-hooks/post-receive
These are changes that have already been applied to our ansible repo, but I'd appreciate review to see if they make sense/look right.
We hit a scenario today that I don't understand where a set of commits pushed by pbrobinson to the 'file' package sent the fedmsg hook into a loop that published some 30k messages before nirik was able to kill it.
There might be a better way than this to detect what commits should and shouldn't be published.  Ideas welcome.
=> Attempt to avoid infinite recursion when finding the list of new revs.

extras/git-hooks/post-receive
This will run us into the limit for recursive calls as jwb just pointed out
in ``#fedora-admin``.
=> Avoid recursively walking the entire git history.

extras/git-hooks/post-receive
We hit an infinite loop in the git hook again tonight which made for a *lot* of
traffic on the bus.
This rolls back the functionality to what we used to have before the move to
gitolite3/rhel7.  It translates as "if someone pushes 5 commits, only publish
about the latest one".
=> No more infinite loops.

fedmsg/meta/__init__.py, fedmsg/meta/base.py
As it stood before, these two kinds of things had different templates:
- Actual conglomerations of multiple messages.
- Fake conglomerations of a single message.
This re-use of code ensures that they will actually look the same.
=> Re-use the produce_template function for consistency.

fedmsg/tests/test_meta.py
Currently, when tests fail it is kind of difficult to figure out exactly
*which* test failed.  This should make it much more easy to jump to the failed
test to inspect it.
=> Add more debug info to test suite failures.

extras/git-hooks/post-receive
We currently publish them newest to oldest which can be really confusing if you
receive them over email.  @remicollet pointed this out in ``#fedora-devel``
last week.
=> Publish git commits in chronological order.

.travis.yml, extras/git-hooks/post-receive, extras/stress/mass-sub.py, fedmsg/commands/__init__.py, fedmsg/commands/collectd.py, fedmsg/commands/tail.py, fedmsg/commands/trigger.py, fedmsg/core.py, fedmsg/crypto/x509.py, fedmsg/meta/base.py, fedmsg/tests/test_commands.py, fedmsg/tests/test_core.py, fedmsg/tests/test_meta.py, fedmsg/tests/test_replay.py, fedmsg/tests/test_utils.py, scripts/fedmsg-map.py, setup.py
This PR contains initial changes to make fedmsg support Python 3. Some notes:
- All tests are green, but I think that doesn't really mean anything :)
- There are still some `isinstance(..., basestring)` calls and since I don't have enough knowledge about fedmsg, I'm not sure what to do with these. They seem to be used as input for `json.loads`, which only takes PY3's `str` type.
- The real problem, I think, will be M2crypto, since that doesn't support Python 3 at all for now. Maybe it would make sense to move to cryptography [1] in long term, since that seems to be *the* Python crypto library for following years.
[1] https://pypi.python.org/pypi/cryptography/
=> Initial shot at Python 3 support

fedmsg/config.py
I updated the docs so they list the correct directories for where it checks the directories. The collections module wasn't being used in config.py either so I removed that
=> Documentation Fix and Flake-8 compliance

fedmsg/meta/base.py
This helps with testing dependent packages (e.g. fedmsg-meta-fedora-infrastructure) on Python 3, which has randomization of sets and maps turned on.
=> Make list_to_series return uniqified items in predictable order.

.gitignore, fedmsg/meta/base.py, setup.py, tox.ini
I ran into problems when deploying the latest release to our rhel7 nodes.  We have python-six-1.3.0 in rhel7, 1.7.3 in EPEL6, and 1.9.0 in fedora/upstream.  These changes get our tests passing on all three scenarios.
=> Take care with python-six

fedmsg/config.py
The order in which configuration files are loaded matters, but fedmsg.config
uses listdir, which returns files in order depending on the filesystem. Sorting
them by name should make things more predictable.
=> Make order of configuration files predictable

fedmsg/meta/__init__.py, fedmsg/tests/test_meta.py
...if they have already been built.
This gets the fedmsg_meta test suite running 31x faster.  Compare before::
(fedmsg_meta)❯ time $(which nosetests) -x                                                                      fedmsg_meta_fedora_infrastructure/git/develop
Ran 3822 tests in 270.822s
OK (SKIP=1638)
----------------------------------------------------------------------
Success!
$(which nosetests) -x  267.30s user 1.32s system 98% cpu 4:33.53 total
And after::
(fedmsg_meta)❯ time $(which nosetests) -x                                                                      fedmsg_meta_fedora_infrastructure/git/develop
Ran 3822 tests in 5.982s
OK (SKIP=1638)
----------------------------------------------------------------------
Success!
$(which nosetests) -x  3.87s user 0.71s system …
=> No need to rebuild fedmsg.meta processors

fedmsg/meta/__init__.py, fedmsg/meta/base.py, fedmsg/meta/logger.py, fedmsg/tests/test_meta.py
This will allow us to render messages in Fedora Hubs that instead of looking like:
"ralph submitted a bodhi update for nethack"
can look like:
"you submitted a bodhi update for nethack"
=> Add a new "subjective" api.

fedmsg/meta/__init__.py, fedmsg/meta/base.py, fedmsg/tests/test_meta.py
This should make it so you can pass an optional ``subject`` to the conglomerate
API and have it behave sensibly.
The subjective API allows you get a string like:
- "you submitted an update"
from a message where you would normally get a string like:
- "ralph submitted an update"
**If** you pass it a ``subject=ralph`` argument.
The conglomerate API allows you to group messages together and get single
strings that represent all of them.  So, instead of getting:
- "ralph submitted update X"
- "ralph submitted update Y"
- "ralph submitted update Z"
You get:
- "ralph submitted updates X, Y, and Z"
----
This patch reconciles those two APIs by letting the conglomerate functions
handle a ``subject`` if one is provided, so you can get something like:
- "you submitted updates X, Y, and Z"
This patch …
=> Reconcile the subjective API with the conglomerate API.

fedmsg/core.py
The cert_index variable is not defined in this branch. Instead, allow it
to be defaulted, but fall back to using the hostname as the key.
=> core: fix gpg signing

.travis.yml, README.rst, doc/FAQ.rst, doc/consuming.rst, doc/deployment.rst, doc/development.rst, fedmsg/commands/tail.py, fedmsg/core.py, setup.py
I found [this semi-ancient issue](https://github.com/fedora-infra/fedmsg/issues/121), and thought it would be a good way to get to know fedmsg better. If it's not relevant anymore, feel free to close out this pull request.
What I've done is split off the non-essential dependencies of fedmsg into what setuptools calls "extras." These are not installed by default but require a command such as ``pip install fedmsg[crypto]``. These allow us to communicate optional dependencies to users. I've created three extras: 'hub', for Moksha and all its dependencies; 'crypto', for the semi-essential cryptographic libraries; and 'all', which is the auto-generated sum of the prior two, plus two other packages which had been previously indicated as non-essential. (It's possible that I misunderstood that …
=> Isolate Moksha and cryptographic dependencies as extras

fedmsg/core.py
This can be extended by other libraries to do something before publishing.
=> Add a pre_fire_hook callback to fedmsg.publish.

README.rst
Added links to [github doc](https://github.com/fedora-infra/fedmsg/tree/develop/doc) and [online doc](https://fedmsg.readthedocs.org/en/latest/)
=> Added links to doc in Readme

fedmsg/meta/__init__.py, fedmsg/meta/announce.py, fedmsg/meta/base.py, fedmsg/meta/logger.py, fedmsg/tests/test_meta.py
As the docstrings indicate, this is different from msg2usernames.
- msg2usernames returns *all* of the users associated with a message and
doesn't distinguish their particular relationships with the event.
- This new msg2agent will return *just* the user who is responsible for the
event.  So, in the case of one user giving karma to another, both users will
be returned by msg2usernames, but just the one who gave the karma will be
returned by msg2agent.
Furthermore, this pull request changes the test framework to allow testing None values.
Previously, if the ``expected_{value}`` on a test was set to ``None``, then
that test would be skipped.  However, that didn't allow us to test that a
value returned *really was None* or not.
This change introduces the use of a sentinel value called …
=> Add a new msg2agent API call to fedmsg.meta.

fedmsg/crypto/x509.py
I've gotten reports from multiple people in recent weeks that their fedmsg
scripts fail and exit when *something happens* and they are unable to pull down
the CRL.  We're not sure why that's failing yet.  It may be a network blip, or
it may be a proxy issue.  In the meantime, we can make fedmsg try a little
harder to get that file before it blows up on the user.
=> Try three times to get the CRL.

fedmsg/crypto/x509.py
Here's the story:
- When we validate an incoming message, we try to check that it is signed with
our CA and that it is not in our CRL.
- When we do that, we check our local cache of those files.  If they are too
old, we grab them fresh from ``https://fedoraproject.org/fedmsg/{crl,ca}.pem``.
- We try to write them to ``/var/cache/fedmsg/foo`` first.  If we don't have
rights to write there, we try to write them instead to ``~/.local/var/cache/fedmsg/foo``.
- When the *next* message comes in, we try to check if
``/var/cache/fedmsg/foo`` is too old.. *but it doesn't exist*.  We wrote it
to ``~/.local/var/cache/fedmsg/foo`` last time.
- We end up pulling down the CRL and the CA cert *every time* for *every
message* if we don't have write access to ``/var/cache/fedmsg/``.
This fixes that so …
=> Stick with alternative cache location.

fedmsg/core.py
setsockopt() accepts, strictly, an int or a bytestring as the
option value. Here we want to use a string as the value, so we
should use setsockopt_string(). I checked all other uses and
they look to be using ints as the option values, so they're OK.
Without this fix, reading the first message from tail_messages
will blow up in Python 3.
See https://pyzmq.readthedocs.org/en/latest/api/zmq.html#zmq.Socket.setsockopt_string .
=> use setsockopt_string when setting a string as the option

fedmsg/core.py
acc7260 was bad - it blows up in Python 2 because there the
value is not a unicode, and setsockopt_string only accepts
unicodes. Making the value a unicode on Python 2 without
crashing in Python 3 attempting to decode a str is annoying,
so instead let's encode the topic and use setsockopt.
This will blow up in Python 3 if the topic is already encoded,
but I don't think that should happen.
=> instead of setsockopt_string, encode topic and use setsockopt

fedmsg/meta/base.py
Mostly just because I want to use it in fedora-hubs.
We'll use this to embed summaries about blog posts and mailing list threads in your feed!
=> Add long_form metadata to the constituents of a grouped event.

fedmsg/meta/__init__.py, fedmsg/meta/base.py
This is for fedora-hubs.
We add an implementation in fedora-infra/fedmsg_meta_fedora_infrastructure#367
which returns a DiffLexer or a MarkdownLexer for certain kinds of messages.
This will let us render the long-form of those messages nicely in your feed.
=> Add the possibility to associate a pygments lexer with a message.

fedmsg.d/ircbot.py, fedmsg/consumers/ircbot.py
i use light terminal, so text in 'light grey' color is unreadable
=> irc: default color configurable

fedmsg/consumers/ircbot.py
This makes it so that, if we are joining 12 channels as 12 bots, we won't try
to do them all at the same time.  We'll connect to one, and then once that is
started we'll wait 1 second and then start the second connection.  The start of
that one will wait 1 second and trigger the third, etc...
=> Cascade IRC connections.

doc/compatibility.rst, doc/index.rst, fedmsg.d/base.py, fedmsg/commands/hub.py, fedmsg/consumers/__init__.py, fedmsg/core.py, fedmsg/meta/base.py
The goal here is to be able to take the litany of apps we've written (FMN, fedmsg-irc, datanommer, fedimg, etc..) and be able to run them in other messaging environments (in particular, the RH unified message bus).
I intend to support:
- The hub/consumer approach.  If you have a fedmsg consumer, it should be able
to listen to messages over other protocols now.
- Publishing with `fedmsg.publish`.  This will only work *from* a fedmsg
consumer.  It will figure out the moksha context and ask *it* to publish on
fedmsg's behalf, thereby publishing over STOMP or AMQP, depending on
configuration.
I explicitly am *not* supporting:
- The naive listening approach, i.e. `fedmsg.tail_messages()`.  It would be a
ton of work and its not worth it atm.  If we find a *really* good reason to
implement …
=> Get fedmsg-hub working on STOMP.

.travis.yml, fedmsg/commands/__init__.py, fedmsg/consumers/__init__.py, fedmsg/tests/test_crypto_switching.py, fedmsg/tests/test_crypto_x509.py, fedmsg/tests/test_hub.py, fedmsg/tests/test_threads.py, setup.cfg, setup.py, tox.ini
I noticed attempting to run ``tox -vv`` and ``python setup.py nosetests`` both failed locally unless a number of packages were manually installed first. I also saw there were a few missing packages in the list of requirements. This change adds those testing requirements in and uses the same list for ``tox``, ``nosetests``, and ``travis``.
=> Fix and unite local and hosted testing

fedmsg/commands/hub.py, fedmsg/tests/test_commands.py
This is a short-term solution to systems running into the maximum open
file descriptor limit.
Signed-off-by: Jeremy Cline <jeremy@jcline.org>
=> Raise the resource limit on open files for fedmsg-hub

fedmsg/consumers/__init__.py
When connecting to a bus without messages being signed, an exception would be raised with the message "Topic envelope mismatch". If signing is turned off, none of the message contents should be examined in the `validate` function.
=> Return earlier when validate_signatures is turned off

doc/compatibility.rst
There's usually no point in cryptographically validating messages from other
busses.  They likely won't bear message certificates and signatures. Other
busses usually use TLS on the connection itself for authentication and
authorization.
=> Document turning off validation for other busses.

doc/development.rst
Updating the 'Development' documentation:
* cryptography library depends on libffi-devel to successfully build
during pip install.
* python-m2crypto doesn't exist on Fedora packaging system. Replacing
the dnf command with m2crypto and swig.
=> Updating dependencies on documentation

tox.ini
It used to be 1.7 on RHEL7, but they upgraded and we only have to worry about 1.9 now.
=> Drop old testcases against old python-six.

fedmsg/consumers/__init__.py
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>
=> Only check for stomp messages after we decoded any ZMQMessage

README.rst, doc/conf.py, doc/index.rst, extras/mediawiki/fedmsg-emit.php, fedmsg/__init__.py, setup.py
Thiis changes the references for Fedora Messaging to Federated Message Bus.
Related to discussions in #373, #383.
=> Library branding

fedmsg/commands/relay.py
If another package happens to be installed in the system, running
`fedmsg-relay` shouldn't inadvertently start that thing.
=> Fedmsg-relay shouldn't run producers.

fedmsg/consumers/__init__.py
Today, when fedmsg-hub starts up, it tries to read in its backlog of
messages from datagrepper in case it missed anything.  It successfully
gets the list, but then every single one of the messages fails
validation.
There's a gist here that demonstrates what needs to happen to make this
work:  https://gist.github.com/ralphbean/b532ad3bc4a8333fa03d4e4e48451885
There are two changes required.  This one here, in fedmsg, and another in
fedora-infra/datanommer#87.
=> Remove artifical keys from datagrepper backlog to pass validation.

fedmsg/config.py
We have a case where we want the environment to be something other than dev,
stg, or prod.  I figure there's not really a reason to enforce any convention
in the code like this.
=> Remove env validation.
